# Generated by Django 4.1.7 on 2023-02-23 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlist',
            name='check_box',
        ),
        migrations.RemoveField(
            model_name='itemlist',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemlist',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('check_box', models.BooleanField(default=False)),
                ('quantity', models.CharField(max_length=50, null=True)),
                ('list_for_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='core.itemlist')),
            ],
        ),
    ]
