# Generated by Django 4.1.7 on 2023-02-24 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_user_alter_item_list_for_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='list_for_items',
        ),
        migrations.AddField(
            model_name='itemlist',
            name='items_for_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ListItems', to='core.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
