# Generated by Django 4.1.7 on 2023-02-24 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_item_list_for_items_itemlist_items_for_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='itemlist',
            name='items_for_list',
        ),
        migrations.AddField(
            model_name='item',
            name='list_for_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listForItems', to='core.itemlist', to_field='title'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
