# Generated by Django 4.1.7 on 2023-02-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_item_quantity_remove_itemlist_items_for_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('list_for_items', 'item'), name='unique_item'),
        ),
    ]
