# Generated by Django 4.1.7 on 2023-02-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_item_quantity_remove_itemlist_items_for_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
