# Generated by Django 4.1.7 on 2023-03-01 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_itemlist_archived_itemlist_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='shared_users',
            field=models.ManyToManyField(related_name='shared_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
