# Generated by Django 4.1.7 on 2023-03-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='active_shopping',
            field=models.BooleanField(default=False),
        ),
    ]
