# Generated by Django 4.1.7 on 2023-03-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_itemlist_active_shopping'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='auth_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
