# Generated by Django 4.1.7 on 2023-03-05 22:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_itemlist_auth_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='auth_id',
            field=models.CharField(default=core.models.random_string_generator, max_length=15),
        ),
    ]
