# Generated by Django 4.1.7 on 2023-03-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_item_missing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
